language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-26
    - extra-android-support
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script:
  - chmod +x ./gradlew
script:
  - ./gradlew build
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken_ANDROID"
  
  on:
    tags: false
    repo: ALGPHELLO/android-build
    branch: 26
branches:
  except:
    - /^(?i:untagged)-.*$/
